function  obj=addMenus(obj)
%ADDMENUS Summary of this function goes here
%   Detailed explanation goes here
       %% get figure handle
        hFuzzy=findall(0,'tag','fuzzyt2');
        %% File
        fileHndl=uimenu(hFuzzy,...
            'Label','File');
        h = uimenu('Parent',fileHndl, ...
            'Label', 'New FIS...');
        %         uimenu('Parent',h, ...
        %             'Label', 'Mamdani', ...
        %             'Tag', 'newmamdani',...
        %             'Callback','');
        uimenu('Parent', h, ...
            'Label', 'Sugeno', ...
            'Callback','');
        % File submenu item Import
        h = uimenu('Parent', fileHndl,'Label', 'Load', ...
            'Separator','on');
        uimenu('Parent',h,'Label', 'From File...', ...
            'Tag', 'openfis',...            
            'Accelerator', 'O', ...
            'Callback',{@loadFromFile obj});
        uimenu('Parent',h,'Label', 'From Workspace...', ...
            'Tag', 'openfis',...
            'Callback',{@loadFromWs obj});
        % File submenu item Export
        h = uimenu('Parent', fileHndl,'Label', 'Save');
        uimenu('Parent',h,'Label', 'To Workspace...', ...
            'Accelerator', 'T', ...
            'Callback', {@saveWs obj});
        uimenu('Parent',h,'Label', 'To File...', ...
            'Tag', 'save',...            
            'Accelerator', 'S', ...
            'Callback',{@saveFile obj});
        % File submenu item Print
        %         uimenu(fileHndl,'Label', 'Print', ...
        %             'Separator','on', ...
        %             'Callback','');
        %         % File submenu item Close
        %         uimenu(fileHndl,'Label', 'Close', ...
        %             'Separator','on', ...
        %             'Callback','');
        
        %% Edit
        h1 = uimenu(hFuzzy, ...
            'Label','Edit');
        %         uimenu(h1, ...
        %             'Callback','', ...
        %             'Label','Open MUT');
        h2 = uimenu('Parent', h1,'Label', 'Add Variable...');
        uimenu(h2, ...
            'Tag','menu_input',...
            'Callback',{@add_input obj},...
            'Label','Input');
        uimenu(h2, ...
            'Tag','menu_output',...
            'Callback',{@add_output obj},...
            'Label','Output');
        %         uimenu(h1, ...
        %             'Callback','', ...
        %             'Label','Remove Selected Variable');
        %         uimenu(h1, ...
        %             'Callback','', ...
        %             'Label','Membership Functions...');
        uimenu(h1, ...
            'Callback','ruleedit2', ...
            'Label','Rules...');
        
        
        %% View
        h1 = uimenu(hFuzzy, ...
            'Label','View');
        uimenu(h1, ...
            'Callback','', ...
            'Label','Rules');
        uimenu(h1, ...
            'Callback','helper.viewSurface', ...
            'Label','Surface');

end

