classdef mfEditor
    %MFEDÝTOR Summary of this class goes here
    %   Detailed explanation goes here
    
    properties
    end
    
    methods
        function obj=mfEditor(cmd,newfis)
            if nargin==0
                % Create it2fls
                newfis=it2flsSession;
                newfis=addvar2_type2(newfis,'input','input1',[-1 1],'init');
                newfis=addvar2_type2(newfis,'input','input2',[-1 1],'init');
                newfis=addvar2_type2(newfis,'output','output1',[0 1],'init');

            end
            
            mfEditorHndl = findall(0,'type','figure','Tag','mfEditor');
            if ~isempty(mfEditorHndl) && isequal(cmd,'initialize')
                figure(mfEditorHndl)
                return
            end
            
            %% colors
            figColor=[0.9 0.9 0.9];
            frmColor=192/255*[1 1 1];
            editColor=255/255*[1 1 1];
            selectColor=[1 0 0];
            unselectColor=[0 0 0];
            inputColor=[1 1 0.93];
            outputColor=[0.8 1 1];
            tickColor=[0.5 0.5 0.5];
            popupColor=192/255*[1 1 1];
            thisit2fls{1}=newfis;
            hMember = figure('Color',[0.8 0.8 0.8], ...
                'MenuBar','none', ...
                'NumberTitle','off', ...
                'Tag','mfEditor', ...
                'UserData',thisit2fls, ...
                'ToolBar','none',...
                'Visible','on',...
                'Name','Membership Function Editor');
            set(hMember,'Units','Normalized','Position',[0.05, 0.1, 0.4, 0.65]);
            movegui(hMember,'west');
            %         set(hMember, 'WindowStyle', 'docked')
            %         setFigDockGroup(hMember, 'Interval Type-2 Fuzzy Logic Systems Toolbox');
            %% Add Menus
            obj=addMenus('','',obj);
            param.CurrMF=-1;
            param.Action='';
            axPos = [0.3 0.5 0.65 0.4];
            mainAxHndl=axes( ...
                'Units','Normalized', ...
                'XColor',tickColor,'YColor',tickColor, ...
                'Color',inputColor, ...
                'Position',axPos, ...
                'Userdata', param, ...
                'Tag','mainaxes', ...
                'Box','on');
            grid on;
            hold on
            titleStr='Membership function plots';
            title(titleStr,'Color','black','FontSize',8);
            
            %% Add buttons and other gui elements
            
            %draw frame
            mainFrmHndl=uicontrol( ...
                'Style','frame', ...
                'Units','Normalized', ...
                'Position',[0.01 0.01 0.98 0.4], ...
                'BackgroundColor',frmColor);
            
            % The VARIABLE PALETTE axes
            axBorder=5;
            axPos=[0.02 0.45 0.23 0.45];
            axHndl=axes( ...
                'Units','Normalized', ...
                'Visible','off', ...
                'XColor',tickColor,'YColor',tickColor, ...
                'Color',[0.8 0.8 0.8], ...
                'Position',axPos, ...
                'Tag','variables', ...
                'Box','on');
            axes(mainAxHndl)
            
            %====================================
            % The VARIABLE frame
            
            varFrmHndl=uicontrol( ...
                'Style','frame', ...
                'Units','Normalized', ...
                'Position',[0.02 0.02 0.35 0.38], ...
                'BackgroundColor',frmColor);
            
            
            %------------------------------------
            % The VARIABLE label field
            
            labelStr='Current Variable';
            pos=[0.04 0.27 0.2 0.1];
            hndl=uicontrol( ...
                'Style','text', ...
                'BackgroundColor',frmColor, ...
                'HorizontalAlignment','left', ...
                'Units','Normalized', ...
                'Position',pos, ...
                'String',labelStr);
            
            %------------------------------------
            % The VARIABLE NAME text field
            name='varname';
            labelStr='Name';
            pos=[0.04 0.21 0.2 0.1];
            hndl=uicontrol( ...
                'Style','text', ...
                'BackgroundColor',frmColor, ...
                'HorizontalAlignment','left', ...
                'Units','Normalized', ...
                'Position',pos, ...
                'String',labelStr);
            
            %------------------------------------
            % The VARIABLE NAME display field
            pos=[0.14 0.21 0.2 0.1];
            hndl=uicontrol( ...
                'Style','text', ...
                'Units','Normalized', ...
                'Position',pos, ...
                'HorizontalAlignment','left', ...
                'BackgroundColor',popupColor, ...
                'String',' ', ...
                'Tag',name);
            
            %------------------------------------
            % The VARIABLE TYPE text field
            labelStr='Type';
            pos=[0.04 0.15 0.2 0.1];
            hndl=uicontrol( ...
                'Style','text', ...
                'BackgroundColor',frmColor, ...
                'HorizontalAlignment','left', ...
                'Units','Normalized', ...
                'Position',pos, ...
                'String',labelStr);
            
            %------------------------------------
            % The VARIABLE TYPE display field
            labelStr=' input| output';
            name='vartype';
            pos=[0.14 0.15 0.2 0.1];
            hndl=uicontrol( ...
                'Style','text', ...
                'HorizontalAlignment','left', ...
                'BackgroundColor',popupColor, ...
                'Units','Normalized', ...
                'Position',pos, ...
                'Tag',name, ...
                'String',labelStr);
            
            %------------------------------------
            % The VARIABLE RANGE text field
            labelStr='Range';
            pos=[0.04 0.085 0.2 0.1];
            hndl=uicontrol( ...
                'Style','text', ...
                'BackgroundColor',frmColor, ...
                'HorizontalAlignment','left', ...
                'Units','Normalized', ...
                'Position',pos, ...
                'String',labelStr);
            
            %------------------------------------
            % The VARIABLE RANGE edit field
            name='varrange';
            pos=[0.17 0.16 0.17 0.03];
            hndl=uicontrol( ...
                'Style','edit', ...
                'Units','Normalized', ...
                'Position',pos, ...
                'HorizontalAlignment','left', ...
                'BackgroundColor',editColor, ...
                'Callback',{@localSelectmf obj}, ...
                'Tag',name);
            
            %------------------------------------
            % The VARIABLE DISPLAY RANGE text field
            labelStr='Display Range';
            pos=[0.04 0.09 0.2 0.03];
            hndl=uicontrol( ...
                'Style','text', ...
                'BackgroundColor',frmColor, ...
                'HorizontalAlignment','left', ...
                'Units','Normalized', ...
                'Position',pos, ...
                'String',labelStr);
            
            %------------------------------------
            % The VARIABLE DISPLAY RANGE edit field
            name='disprange';
            pos=[0.17 0.085 0.17 0.03];
            hndl=uicontrol( ...
                'Style','edit', ...
                'Units','Normalized', ...
                'Position',pos, ...
                'HorizontalAlignment','left', ...
                'BackgroundColor',editColor, ...
                'Callback',{@disprange obj}, ...
                'Tag',name);
            
            %====================================
            % The MF frame
            frmPos=[0.4 0.02 0.58 0.377];
            mfFrmHndl=uicontrol( ...
                'Style','frame', ...
                'Units','Normalized', ...
                'Position',frmPos, ...
                'BackgroundColor',frmColor);
            
            % Upper frame
            frmPos=[0.43 0.2 0.44 0.15];
            mfFrmHndl=uicontrol( ...
                'Style','frame', ...
                'Units','Normalized', ...
                'Position',frmPos, ...
                'BackgroundColor',frmColor,...
                'tag','UpperFrame');
            
            % Lower frame
            frmPos=[0.43 0.04 0.44 0.15];
            mfFrmHndl=uicontrol( ...
                'Style','frame', ...
                'Units','Normalized', ...
                'Position',frmPos, ...
                'BackgroundColor',frmColor,...
                'tag','LowerFrame');
            
            
            
            %------------------------------------
            % The MEMBERSHIP FUNCTION text field
            labelStr='Current Membership Function (click on MF to select)';
            pos=[0.45 0.35 0.4 0.03];
            uicontrol( ...
                'Style','text', ...
                'BackgroundColor',frmColor, ...
                'HorizontalAlignment','left', ...
                'Units','Normalized', ...
                'Position',pos, ...
                'String',labelStr);
            
            %         callbackStr='paint_intervals';
            %         labelStr = 'Fill';
            %         name='FillInt';
            %         pos=[0.92 0.1 0.04 0.2];
            %         hndl=uicontrol( ...
            %             'Style','PushButton', ...
            %             'Units','Normalized', ...
            %             'Position',pos, ...
            %             'HorizontalAlignment','left', ...
            %             'BackgroundColor',[1 1 1], ...
            %             'Tag',name, ...
            %             'Callback',callbackStr, ...
            %             'String',labelStr );
            
            %------------------------------------
            % The MF Name text label
            labelStr='Name ';
            pos=[0.45 0.295 0.1 0.02];
            hndl=uicontrol( ...
                'Style','text', ...
                'HorizontalAlignment','left', ...
                'BackgroundColor',frmColor, ...
                'Units','Normalized', ...
                'Position',pos, ...
                'String',labelStr);
            
            %------------------------------------
            % The MF NAME edit field
            
            labelStr = 'test';
            name='mfname';
            pos=[0.75 0.29 0.1 0.025];
            hndl=uicontrol( ...
                'Style','edit', ...
                'Units','Normalized', ...
                'Position',pos, ...
                'HorizontalAlignment','left', ...
                'BackgroundColor',editColor, ...
                'Tag',name, ...
                'Callback',{@mfname obj}, ...
                'String','testval');
            
            %------------------------------------
            % The MF Name text label
            labelStr='Name Lower';
            pos=[0.45 0.26 0.1 0.02];
            hndl=uicontrol( ...
                'Style','text', ...
                'HorizontalAlignment','left', ...
                'BackgroundColor',frmColor, ...
                'Units','Normalized', ...
                'Position',pos, ...
                'String',labelStr);
            
            %------------------------------------
            % The MF NAME edit field

            labelStr = 'test';
            name='mfname Lower';
            pos=[0.75 0.26 0.1 0.025];
            hndl=uicontrol( ...
                'Style','edit', ...
                'Units','Normalized', ...
                'Position',pos, ...
                'HorizontalAlignment','left', ...
                'BackgroundColor',editColor, ...
                'Tag',name, ...
                'Callback',{@mfname obj}, ...
                'String','testval');
            
            % Crisp Interval Text
            pos=[0.6,0.3,0.16,0.03];
            hndl=uicontrol( ...
                'Style','text', ...
                'HorizontalAlignment','left', ...
                'BackgroundColor',frmColor, ...
                'Units','Normalized', ...
                'Position',pos, ...
                'String','Choose Output Type');
            
            % Radio buttons for crisp interval selection
            ChkBoxHandle=uicontrol('style','radiobutton',...
                'units','Normalized',...
                'position',[0.5,0.22,0.09,0.04],...
                'string','Crisp',...
                'tag','CheckboxCrips',...
                'Callback','helper.setCrispInterval(''crisp'')',...
                'BackgroundColor',frmColor);
            
            ChkBoxHandle=uicontrol('style','radiobutton',...
                'units','Normalized',...
                'position',[0.7,0.22,0.09,0.04],...
                'string','Interval',...
                'tag','CheckboxInterval',...
                'Callback','helper.setCrispInterval(''interval'')',...
                'BackgroundColor',frmColor);
            
            
            % Grid Frame
            frmPos=[0.88 0.23 0.09 0.12];
            mfFrmHndl=uicontrol( ...
                'Style','frame', ...
                'Units','Normalized', ...
                'Position',frmPos, ...
                'BackgroundColor',frmColor,...
                'tag','GridFrame');
            
            % Grid Text
            labelStr='Grid';
            pos=[0.91 0.32 0.05 0.02];
            hndl=uicontrol( ...
                'Style','text', ...
                'HorizontalAlignment','left', ...
                'BackgroundColor',frmColor, ...
                'Units','Normalized', ...
                'Position',pos, ...
                'String',labelStr);
            % Radio buttons for grid selection
            uicontrol('style','radiobutton',...
                'units','Normalized',...
                'position',[0.9,0.28,0.05,0.03],...
                'string','On',...
                'tag','gridon',...
                'Callback',{@grid obj 'on'},...
                'BackgroundColor',frmColor,...
                'Value',1);
            
            uicontrol('style','radiobutton',...
                'units','Normalized',...
                'position',[0.9,0.24,0.05,0.03],...
                'string','Off',...
                'tag','gridoff',...
                'Callback',{@grid obj 'off'},...
                'BackgroundColor',frmColor,...
                'Value',0);
            
            
            
            %------------------------------------
            % The MF TYPE text label
            labelStr='Type ';
            pos=[0.45 0.165 0.1 0.03];
            hndl=uicontrol( ...
                'Style','text', ...
                'HorizontalAlignment','left', ...
                'BackgroundColor',frmColor, ...
                'Units','Normalized', ...
                'Position',pos, ...
                'String',labelStr);
            
            % The MF TYPE text label
            labelStr='Type Lower';
            pos=[0.45 0.12 0.1 0.03];
            hndl=uicontrol( ...
                'Style','text', ...
                'HorizontalAlignment','left', ...
                'BackgroundColor',frmColor, ...
                'Units','Normalized', ...
                'Position',pos, ...
                'String',labelStr);
            
            %------------------------------------
            % The MF TYPE popup menu
            labelStr1=str2mat(' trimf',' trapmf',' gbellmf',' gaussmf',' gauss2mf',' sigmf');
            labelStr1=str2mat(labelStr1,' dsigmf',' psigmf',' pimf',' smf',' zmf');
            labelStr2=str2mat(' constant',' linear');
            name='mftype';
            pos=[0.75 0.165 0.1 0.03];
            hndl=uicontrol( ...
                'Style','popupmenu', ...
                'Units','Normalized', ...
                'UserData',labelStr2, ...
                'Position',pos, ...
                'HorizontalAlignment','left', ...
                'BackgroundColor',popupColor, ...
                'Callback',{@mftype obj}, ...
                'String',labelStr1, ...
                'Tag',name);

            name='mftypelower';
            pos=[0.75 0.12 0.1 0.03];
            hndl=uicontrol( ...
                'Style','popupmenu', ...
                'Units','Normalized', ...
                'UserData',labelStr2, ...
                'Position',pos, ...
                'HorizontalAlignment','left', ...
                'BackgroundColor',popupColor, ...
                'Callback',{@mftype obj}, ...
                'String',labelStr1, ...
                'Tag',name);
            
            %------------------------------------
            % The MF PARAMS text label
            labelStr='Params';
            pos=[0.45 0.12 0.2 0.03];
            hndl=uicontrol( ...
                'Style','text', ...
                'HorizontalAlignment','left', ...
                'BackgroundColor',frmColor, ...
                'Units','Normalized', ...
                'Position',pos, ...
                'String',labelStr);
            
            %------------------------------------
            % The MF PARAMS edit field
            name='mfparams';
            pos=[0.65 0.12 0.2 0.03];
            hndl=uicontrol( ...
                'Style','edit', ...
                'HorizontalAlignment','left', ...
                'BackgroundColor',editColor, ...
                'Units','Normalized', ...
                'Position',pos, ...
                'Callback',{@mfparams obj}, ...
                'Tag',name);
            
            % The MF PARAMS2 text label
            labelStr='Params Lower';
            pos=[0.45 0.06 0.2 0.03];
            hndl=uicontrol( ...
                'Style','text', ...
                'HorizontalAlignment','left', ...
                'BackgroundColor',frmColor, ...
                'Units','Normalized', ...
                'Position',pos, ...
                'String',labelStr);
            
            % The MF PARAMS2 edit field
            name='mfparams2';
            pos=[0.65 0.06 0.2 0.03];
            hndl=uicontrol( ...
                'Style','edit', ...
                'HorizontalAlignment','left', ...
                'BackgroundColor',editColor, ...
                'Units','Normalized', ...
                'Position',pos, ...
                'Callback',{@mfparams obj}, ...
                'Tag',name);
            
            name='numpoints';
            pos=[0.851 0.94 0.10 0.05];
            hndl=uicontrol( ...
                'Style','edit', ...
                'HorizontalAlignment','right', ...
                'BackgroundColor',editColor, ...
                'Units','normal', ...
                'Position',pos, ...
                'String', '181', ...
                'Callback',{@plotmfs obj}, ...
                'Visible','off',...
                'Tag',name);
            pos=[0.74 0.94 0.10 0.05];
            
            hndl=uicontrol( ...
                'Style','text', ...
                'HorizontalAlignment','right', ...
                'BackgroundColor', figColor, ...
                'Units','normal', ...
                'Position',pos, ...
                'FontSize',8, ...
                'String', 'plot points:', ...
                'Visible', 'off',...
                'Tag','pointlabel');
            
            
            
            
            obj=plotvars(obj);
            obj=selectvar('','',obj);
            obj=plotmfs(obj);
            
        end
        
    end
end
    
